name: Testing API
on: [push,pull_request]
jobs: 
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependecies
        run: |
          pip install dvc_gs
          pip install -r requirements_test.txt
      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python3 Utilities/setter.py)
          dvc pull model/model.pkl -r models_track
          pytest tests.py
